Changing the JATS creation to a DOM based model
pkp/jatsTemplate pull request #26
Opened 2023-06-06 21:24 UTC by withanage

-  Still not yet final

2023-06-07 22:20 UTC, asmecher requested changes
Looks great! Some initial comments; I'll take a second kick at it with some in-use testing once these are resolved.

2023-06-07 22:20 UTC, asmecher commented on classes/Article.php
> +     * @param $elementName string
The self-documentation doesn't add anything that's not already in the type hinting; in cases like this, it's better to avoid the duplication and just let the type declarations be definitive.

2023-06-07 22:20 UTC, asmecher commented on classes/Article.php
> +<?php
All classes should have a standard code header.

2023-06-07 22:20 UTC, asmecher commented on classes/Article.php
> +    public function convertToXml(&$record) :bool|\DOMDocument
The reference here is unnecessary, I'm pretty sure. It's best not to use references unless they're necessary.

2023-06-07 22:20 UTC, asmecher commented on classes/ArticleBack.php
> +//        dd($citations);
(debug code needs removal)

2023-06-07 22:20 UTC, asmecher commented on classes/Article.php
> +    public function appendChildToParent($parent, $child)
I think this is useful for cases where `$child` isn't set, right? Off the top of my head, `$parent` should always be set. I'm not a big fan of conditionals like this that allow for code to silently be skipped on what might be an error condition, plus it's strange to put a helper function in this class when it's also used in other places in this PR. I think there are relatively few cases where the child node doesn't exist, and would rather those were explicitly handled.

2023-06-07 22:20 UTC, asmecher commented on tests/functional/ArticleBackTest.php
> +//    public function testCreateIfRecordsAvailable(){
Needs fixing or removal.

2023-06-07 22:20 UTC, asmecher commented on tests/functional/ArticleBodyTest.php
> +//    public function testCreateIfFileExists(){
Needs fixing or removal.

2023-06-07 22:20 UTC, asmecher commented on tests/functional/ArticleBackTest.php
> +<?php
It's great to have tests for this plugin! Could you get these going in a CI environment with either Travis or Github Actions?

2023-06-07 23:15 UTC, withanage commented on classes/Article.php
> +<?php
sure, we will put the general plugin header here

2023-06-07 23:19 UTC, withanage commented on tests/functional/ArticleBackTest.php
> +<?php
I would write the github actions for this, before asking the final reviwe.  It will be very similar to travis 

https://github.com/withanage/rosetta/blob/stable-3_3_0/.github/workflows/validate-sip.yml

2023-06-08 09:04 UTC, ipula commented on classes/Article.php
> +     * @param $elementName string
@asmecher shall we remove all the parameters documentation for the type hint parameters

2023-07-15 00:41 UTC, asmecher requested changes
This is getting a lot closer, thanks! I've added a few comments.

2023-07-15 00:41 UTC, asmecher commented on classes/ArticleFront.php
> +        $selfUriElement= $article->createDom('self-uri', strip_tags($ccBadge) , ['xlink:href'=>htmlspecialchars($request->url($journal->getPath(), 'article', 'view', $submission->getBestArticleId())
The `&&` logic here looks wrong; did something get garbled when adapting this from string concatenation?

2023-07-15 00:41 UTC, asmecher commented on classes/Article.php
> +    public function createDom(string $elementName, $elementValue = null, array $attributes = []):\DOMElement
You're probably going to hate this suggestion -- sorry, and I do see what you're doing here! -- but I would prefer to just use standard DOM functions with function chaining, rather than adding a nonstandard `createDom` function here that gets called strangely from the other classes.

Helper functions often are alienating to outside developers and obscure some of the tricky aspects. For example, many (but not all!) calls to `createDom` wrap content with `htmlspecialchars`. `htmlspecialchars` relies on the current PHP charset configuration, even though this document is hard-coded (as it should be) UTF-8; it's safer to create elements with appropriately escaped content using just the DOM tools like this:
```php
$mixedCitationElement = $this->createElement('mixed-citation')
    ->appendChild($this->createTextNode($citation->getRawCitation()));
```
It's clear to an outside developer what this is doing without having to refer to `createDom`, and it's not meaningfully longer or less readable than [e.g.](https://github.com/pkp/jatsTemplate/pull/26/files#diff-0a3cd86a692ad7086a22108f9b072fa3bfc3f88b5077c27bd516c6d8e99a7ab1R40):
```php
$mixedCitationElement = $article->createDom('mixed-citation', htmlspecialchars($citation->getRawCitation()) , []);
```

Things do get a little longer when creating elements with values and attributes, but that's only done in a few cases, and never with many attributes. For example, the `self-uri` element [with `createDom`](https://github.com/pkp/jatsTemplate/pull/26/files#diff-11e457ccd0f48a0b36bf17dbf4eb71477dc3b75ddf8b9be8595fea6fe3516fb3R310) is:
```php
$selfUriElement= $article->createDom('self-uri', strip_tags($ccBadge) , ['xlink:href'=>htmlspecialchars($request->url($journal->getPath(), 'article', 'view', $submission->getBestArticleId()) != null && $request->url($journal->getPath(), 'article', 'view', $submission->getBestArticleId()))]);
```
Reformatted for readability that might be...
```php
$selfUriElement = $article->createDom(
    'self-uri',
    strip_tags($ccBadge),
    [
        'xlink:href' => htmlspecialchars($request->url($journal->getPath(), 'article', 'view', $submission->getBestArticleId()) != null && $request->url($journal->getPath(), 'article', 'view', $submission->getBestArticleId()))
    ]
);
```
(Actually, I think something got garbled in adapting that line of code from string concatenation to DOM. But I've commented on that further down, so ignoring ignoring that for now...)

Using pure DOM functions, this would be (untested)...
```php
$selfUriElement = $this->createElement('self-uri')->appendChild($this->createTextNode(strip_tags($ccBadge)))
    ->setAttribute('xlink:href', $request->url(...));
```
In particular the escaping requirements of this code will be tricky -- some strings are HTML and need conversion to text followed by escaping, some will preserve HTML in a filtered form and then shouldn't be escaped, etc. -- and it's much easier to maintain if the developer can tell at a glance exactly what's happening when building the DOM.

Here's a decent example of the problem I'm trying to avoid, and a readable solution to it: https://stackoverflow.com/questions/6717098/create-a-complex-structure-with-domdocument

2023-07-15 00:41 UTC, asmecher commented on classes/ArticleFront.php
> +        $selfUriElement= $article->createDom('self-uri', strip_tags($ccBadge) , ['xlink:href'=>htmlspecialchars($request->url($journal->getPath(), 'article', 'view', $submission->getBestArticleId())
Also, I'm pretty sure applying `htmlspecialchars` to an attribute that's eventually set with `DOMElement::setAttribute` will lead to double-escaping.

2023-07-17 07:49 UTC, withanage commented on classes/Article.php
> +    public function createDom(string $elementName, $elementValue = null, array $attributes = []):\DOMElement
@asmecher

thanks fotr the detailed answer.!    We will  write the functions using standard dom functions.

2023-08-01 18:56 UTC, asmecher commented
@withanage and @ipula, is this ready for another review?

2023-08-01 19:26 UTC, withanage commented
@asmecher yes
Ipula rewrote this  to the standard dom functions

2023-08-03 23:44 UTC, asmecher commented
See: https://github.com/pkp/jatsTemplate/pull/29

2023-08-03 23:44 UTC, closed without merging