[JatsTemplate][main] #7505 Initial Commit Upload - Delete - Download JATS File
pkp/jatsTemplate pull request #41
Opened 2023-11-24 10:47 UTC by defstat

2023-11-24 17:59 UTC, asmecher requested changes
Thanks, @defstat! Just a few questions/comments.

2023-11-24 17:59 UTC, asmecher commented on classes/Article.php
> +            $this->convertToXml($record);
I'd suggest moving this call outside of the constructor entirely; let the existing (JATSTemplatePlugin) use case call an additional function to perform the conversion, just like you've done for the new use case. (Call it e.g. `convertToOai`.)

2023-11-24 17:59 UTC, asmecher commented on classes/Article.php
> +        return $this->loadXml($convertedXML);
It would be nice to cut down on the load/save cycle here; I'm not sure why it was written that way, but I don't think it's necessary.

2023-11-24 17:59 UTC, asmecher commented on classes/ArticleFront.php
> +        if (!$datePublished) $datePublished = strtotime('0001-01-01');
Is there a way to properly indicate to the JATS output that we don't yet have a publication date?

2023-11-24 17:59 UTC, asmecher commented on classes/ArticleFront.php
> +        $dispatcher->addRouterName('\APP\core\PageRouter', PKPApplication::ROUTE_PAGE);
Is this necessary?

2023-11-24 18:13 UTC, defstat commented on classes/Article.php
> +            $this->convertToXml($record);
My first instinct was also to remove it - on second thought, and because the constructor is being used in a way that I couldn't figure out why (but accepting that it has a reason), I followed this "safe" way. 

I will refactor it.

2023-11-24 18:17 UTC, defstat commented on classes/ArticleFront.php
> +        if (!$datePublished) $datePublished = strtotime('0001-01-01');
Perhaps [this](https://jats.nlm.nih.gov/archiving/tag-library/1.2/element/pub-date-not-available.html). I will refactor the JATS Template

2023-11-24 18:23 UTC, defstat commented on classes/ArticleFront.php
> +        $dispatcher->addRouterName('\APP\core\PageRouter', PKPApplication::ROUTE_PAGE);
The problem here is that this is called from an API endpoint. The `Application::getRequest()` returns an APIRouter does not seem to [like ](https://github.com/pkp/pkp-lib/blob/main/classes/core/APIRouter.php#L161) the url creation with parts other than the necessary for the endpoints. 

This was a way to bypass that.

2023-11-24 19:26 UTC, defstat commented on classes/Article.php
> +            $this->convertToXml($record);
Fixed

2023-11-24 19:27 UTC, defstat commented on classes/Article.php
> +        return $this->loadXml($convertedXML);
Fixed

2023-11-24 19:29 UTC, defstat commented on classes/ArticleFront.php
> +        if (!$datePublished) $datePublished = strtotime('0001-01-01');
Fixed

Right now if a publication is assigned to an issue but is not published, a publication date is added to JATS. Not sure if that is correct though - I would expect that if the publication is not yet published, the publication date should be null, and not retrieved by the assigned issue

2023-11-25 00:12 UTC, asmecher commented on classes/ArticleFront.php
> +        if (!$datePublished) $datePublished = strtotime('0001-01-01');
It should be possible to omit the `pub-date` element if the content is not yet published. ([JATS reference for article metadata](https://jats.nlm.nih.gov/archiving/tag-library/1.2/element/article-meta.html))

2023-11-25 00:14 UTC, asmecher commented on classes/ArticleFront.php
> +        $dispatcher->addRouterName('\APP\core\PageRouter', PKPApplication::ROUTE_PAGE);
You should be able to use:
```php
$router = $request->getRouter();
$dispatcher = $router->getDispatcher();
$url = $dispatcher->url(...)
```
...rather than instantiating and configuring your own dispatcher.

2023-11-25 11:59 UTC, defstat commented on classes/ArticleFront.php
> +        if (!$datePublished) $datePublished = strtotime('0001-01-01');
I will remove the added `pub-date-not-available` element. 

still wondering about that 
> Right now if a publication is assigned to an issue but is not published, a publication date is added to JATS. Not sure if that is correct though - I would expect that if the publication is not yet published, the publication date should be null, and not retrieved by the assigned issue

2023-11-25 12:09 UTC, defstat commented on classes/ArticleFront.php
> +        $dispatcher->addRouterName('\APP\core\PageRouter', PKPApplication::ROUTE_PAGE);
You are right. 

Fixed

2023-11-28 16:33 UTC, asmecher commented on classes/ArticleFront.php
> +        if (!$datePublished) $datePublished = strtotime('0001-01-01');
Agreed, the publication date should not be added if the issue is not yet published.

2023-12-05 22:28 UTC, asmecher approved these changes
Looks good, @defstat!

2023-12-07 11:58 UTC, defstat commented
Closed in favor of pkp/jatsTemplate#42

2023-12-07 11:58 UTC, closed without merging